from enum import Enum


class UserRole(str, Enum):
    PASSENGER = "PASSENGER"
    DRIVER = "DRIVER"
    DISPATCHER = "DISPATCHER"
    ADMIN = "ADMIN"


class RouteStatus(str, Enum):
    ON_TIME = "ON_TIME"
    DELAYED = "DELAYED"
    CANCELLED = "CANCELLED"


class JourneyStatus(str, Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    DELAYED = "DELAYED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReportCategory(str, Enum):
    VEHICLE_BREAKDOWN = "VEHICLE_BREAKDOWN"
    TRAFFIC_JAM = "TRAFFIC_JAM"
    ANIMAL = "ANIMAL"
    OVERCROWDED = "OVERCROWDED"
    DIRTY_VEHICLE = "DIRTY_VEHICLE"
    MEDICAL_HELP = "MEDICAL_HELP"


class TicketType(str, Enum):
    MONTHLY = "MONTHLY"
    DAILY = "DAILY"
    TWO_HOUR = "TWO_HOUR"
    FOUR_HOUR = "FOUR_HOUR"
    ONE_HOUR = "ONE_HOUR"
    THIRTY_MIN = "THIRTY_MIN"
    TRAIN_ROUTE = "TRAIN_ROUTE"


class NotificationType(str, Enum):
    DISABLED_PERSON_JOURNEY = "DISABLED_PERSON_JOURNEY"
    ALTERNATIVE_ROUTE_SUGGESTION = "ALTERNATIVE_ROUTE_SUGGESTION"
    JOURNEY_REMINDER = "JOURNEY_REMINDER"
